@HostAddress = http://localhost:5187

### Add an Evacuation Zone A
POST {{HostAddress}}/api/evacuation-zones
Content-Type: application/json

{
  "zoneId": "Z1",
  "locationCoordinates": {
    "latitude": 13.7563,
    "longitude": 100.5018
  },
  "numberOfPeople": 100,
  "urgencyLevel": 4
}


### Add an Evacuation Zone B
POST {{HostAddress}}/api/evacuation-zones
Content-Type: application/json

{
  "zoneId": "Z2",
  "locationCoordinates": {
    "latitude": 13.7367,
    "longitude": 100.5231
  },
  "numberOfPeople": 50,
  "urgencyLevel": 5
}

### Add a bus 
POST {{HostAddress}}/api/vehicles
Content-Type: application/json

{
  "vehicleId": "V1",
  "capacity": 40,
  "type": "Bus",
  "LocationCoordinates": {
    "latitude": 13.7650,
    "longitude": 100.5381
  },
  "speed": 60
}

### Add a van 
POST {{HostAddress}}/api/vehicles
Content-Type: application/json

{
  "vehicleId": "V2",
  "capacity": 20,
  "type": "Van",
  "LocationCoordinates": {"latitude": 13.7320,"longitude": 100.5200},
  "speed": 50

}

###  "isAvailable": true
### Generate Evacuation Plan
POST {{HostAddress}}/api/Evacuations/plan
Accept: application/json

### Get Evacuation Status
GET {{HostAddress}}/api/Evacuations/status
Accept: application/json

### Update Status
# The API endpoint requirement does not specific that it must be body or query or params 
# So I use query because it is simple, i don't have to create Dto at all.
PUT {{HostAddress}}/api/Evacuations/update?zoneId=Zone-A&evacuatedCount=50&vehicleId=Bus-01
Accept: application/json

### Clear Data
DELETE {{HostAddress}}/api/Evacuations/clear
Accept: application/json