// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using evacPlanMoni.infras.dbcontexts;

#nullable disable

namespace evacPlanMoni.Migrations
{
    [DbContext(typeof(EvacuationDbContext))]
    partial class EvacuationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("evacPlanMoni.entities.EvacuationPlan", b =>
                {
                    b.Property<string>("ZoneId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("VehicleId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("ETAHours")
                        .HasColumnType("double precision");

                    b.Property<int>("PeopleToEvacuate")
                        .HasColumnType("integer");

                    b.HasKey("ZoneId", "VehicleId");

                    b.ToTable("EvacuationPlans", (string)null);
                });

            modelBuilder.Entity("evacPlanMoni.entities.EvacuationStatus", b =>
                {
                    b.Property<string>("ZoneId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastVehicleUsed")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RemainingPeople")
                        .HasColumnType("integer");

                    b.Property<int>("TotalEvacuated")
                        .HasColumnType("integer");

                    b.HasKey("ZoneId");

                    b.ToTable("EvacuationStatuses", (string)null);
                });

            modelBuilder.Entity("evacPlanMoni.entities.EvacuationZone", b =>
                {
                    b.Property<string>("ZoneId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("TotalPeople")
                        .HasColumnType("integer");

                    b.Property<int>("UrgencyLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("ZoneId");

                    b.HasIndex("UrgencyLevel");

                    b.ToTable("EvacuationZones", (string)null);
                });

            modelBuilder.Entity("evacPlanMoni.entities.Vehicle", b =>
                {
                    b.Property<string>("VehicleId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Speed")
                        .HasColumnType("double precision");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("VehicleId");

                    b.ToTable("Vehicles", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
